global:
  http_config:
    tls_config:
      insecure_skip_verify: true

route:
  group_by: [AlertaCPU]
  receiver: "smscpu"

receivers:
  - name: "smscpu"
    webhook_configs:
      - url: https://morfeu:4443/AeC.WebServices.SMSAPI/v2/sms.asp
#      - url: https://aec.com.br.webhook.office.com/webhookb2/7fead428-a8a1-417a-9a66-d1fce1c8133b@8106d8af-7489-49c4-a814-f495064fde59/IncomingWebhook/70a5145cdeea45bfb5935eb35cfa46a6/6669b316-80a9-4ccf-9315-509bd76da785
        send_resolved: true


