version: '2'
services:
  prometheus:
     image: prom/prometheus:latest
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
       - ./prometheus_db:/var/lib/prometheus
       - ./alert.rules:/etc/prometheus/alert.rules

     command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - '--web.enable-lifecycle'
       - '--storage.tsdb.path=data/'
       - '--storage.tsdb.retention.time=30d'
     ports:
       - '9090:9090'


  alertmanager:
    image: prom/alertmanager
    ports:
    - '9093:9093'
    volumes:
    - './alertmanager/:/etc/alertmanager/'
    restart: always
    command:
    - '--config.file=/etc/alertmanager/config.yml'
    - '--storage.path=/alertmanager'

#  node-exporter:
#    pid: "host"
#    volumes:
#    - /:/host:ro,rslave
#    command:
#    - '--path.rootfs=/host'
#    image: prom/node-exporter
#    ports:
#       - '9100:9100'
           
        
  grafana:
   image: grafana/grafana:latest
   container_name: monitoring_grafana
   restart: unless-stopped
   links:
     - prometheus:prometheus
   volumes:
     - ./data/grafana:/var/lib/grafana
     - ./data/grafana.ini:/etc/grafana/grafana.ini
   environment:
     - GF_SECURITY_ADMIN_PASSWORD=102010
     - GF_USERS_ALLOW_SIGN_UP=false
     - GF_SERVER_DOMAIN=myrul.com
     - GF_SMTP_ENABLED=true
     - GF_SMTP_HOST=smtp.gmail.com:587
     - GF_SMTP_USER=myadrress@gmail.com
     - GF_SMTP_PASSWORD=mypassword
     - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
     - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=true
     - GF_APP_TLS_SKIP_VERIFY_INSECURE=true
   ports:
     - "3000:3000" 
           
